# Dependencias
FROM node:21-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock.json ./

RUN npm install



# Builder construye la aplicacion

FROM node:21-alpine3.19 as build

ARG ORDERS_DATABASE_URL
ENV DATABASE_URL=$ORDERS_DATABASE_URL

RUN echo "database_url ::: $ORDERS_DATABASE_URL";

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules

COPY . .

RUN npx prisma migrate deploy
RUN npx prisma generate

RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force


# Crear la imagen final de docker

FROM node:21-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

# Cpiar la carpeta de distribucion carpeta dist
COPY --from=build /usr/src/app/dist ./dist
# Copiar la carpeta de prisma
#COPY --from=build /usr/src/app/prisma ./prisma

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD ["node", "dist/main.js"]
