services:
  orders-db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5437:5432
